# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM hub.adsw.io/library/gpdb6_regress:adb-6.x-dev
RUN gpdb_src/concourse/scripts/setup_gpadmin_user.bash
RUN mkdir -p /data/gpdata/master /data/gpdata/primary /data/gpdata/mirror && chmod -R 755 /data && \
    source gpdb_src/concourse/scripts/common.bash  && \
    chown -R gpadmin:gpadmin /data && \
    chown -R gpadmin:gpadmin /home/gpadmin && install_gpdb

RUN yum install -y lz4-devel libzstd-devel bzip2-devel ksh python2-pyyaml

ADD ./start_adb.sh /home/gpadmin/start_adb.sh
ADD ./healthcheck.sh /home/gpadmin/healthcheck.sh
RUN chmod +x /home/gpadmin/start_adb.sh
RUN chmod +x /home/gpadmin/healthcheck.sh
ENTRYPOINT ["/home/gpadmin/start_adb.sh"]
