# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.8"
services:
    mdw:
        image: "hub.adsw.io/java/gpdb6-java-ubuntu:latest"
        restart: on-failure:3
        working_dir: /home/gpadmin
        hostname: mdw
        ports:
            - "6000:6000"
        environment:
            - DOCKER_GP_CLUSTER_HOSTS=mdw,smdw,sdw1,sdw2
            - DOCKER_GP_MASTER_SERVER=mdw
            - DOCKER_GP_STANDBY_SERVER=smdw
            - DOCKER_GP_SEGMENT_SERVERS=sdw1,sdw2
            - DOCKER_GP_PRIMARY_SEGMENTS_PER_HOST=2
            - DOCKER_GP_WITH_MIRROR=true
            - HZ_NETWORK_JOIN_TCPIP_MEMBERS=adb,sdw1,sdw2
            - ADB_CLUSTER_NAME=primary_cluster
            - ADB_CLUSTER_GUID=deadbeef-feed-beef-dead-baddadfeedad
            - AGENT_JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -Xlog:gc*,safepoint:gc.log:time,uptime:filecount=100,filesize=50M -Xmx2g -Xms256m
        depends_on:
            - sdw1
            - sdw2
            - smdw
        healthcheck:
            test: 'bash /home/gpadmin/healthcheck.sh true 2 true'
            interval: 10s
            timeout: 1s
            retries: 20
        entrypoint: ["bash", "start_adb_service.sh"]
        privileged: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        sysctls:
            kernel.sem: 500 1024000 200 4096
            net.unix.max_dgram_qlen: 4096
        volumes:
          - "./healthcheck.sh:/home/gpadmin/healthcheck.sh:rw"
          - "./start_adb_service.sh:/home/gpadmin/start_adb_service.sh:rw"
        networks:
          - nifinet

    sdw1:
        image: "hub.adsw.io/java/gpdb6-java-ubuntu:latest"
        restart: on-failure:3
        privileged: true
        hostname: sdw1
        healthcheck:
            test: 'bash /home/gpadmin/healthcheck.sh false 2 true'
        environment:
            - DOCKER_GP_CLUSTER_HOSTS=mdw,smdw,sdw1,sdw2
            - DOCKER_GP_MASTER_SERVER=mdw
            - DOCKER_GP_STANDBY_SERVER=smdw
            - DOCKER_GP_SEGMENT_SERVERS=sdw1,sdw2
            - DOCKER_GP_PRIMARY_SEGMENTS_PER_HOST=2
            - DOCKER_GP_WITH_MIRROR=true
            - HZ_NETWORK_JOIN_TCPIP_MEMBERS=adb,sdw1,sdw2
            - ADB_CLUSTER_NAME=primary_cluster
            - ADB_CLUSTER_GUID=deadbeef-feed-beef-dead-baddadfeedad
            - AGENT_JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -Xlog:gc*,safepoint:gc.log:time,uptime:filecount=100,filesize=50M -Xmx2g -Xms256m
        entrypoint: ["bash", "start_adb_service.sh"]
        extra_hosts:
            - "host.docker.internal:host-gateway"
        sysctls:
            kernel.sem: 500 1024000 200 4096
            net.unix.max_dgram_qlen: 4096
        volumes:
          - "./healthcheck.sh:/home/gpadmin/healthcheck.sh:rw"
          - "./start_adb_service.sh:/home/gpadmin/start_adb_service.sh:rw"
        networks:
          - nifinet

    sdw2:
        image: "hub.adsw.io/java/gpdb6-java-ubuntu:latest"
        restart: on-failure:3
        privileged: true
        hostname: sdw2
        healthcheck:
            test: 'bash /home/gpadmin/healthcheck.sh false 2 true'
        environment:
            - DOCKER_GP_CLUSTER_HOSTS=mdw,smdw,sdw1,sdw2
            - DOCKER_GP_MASTER_SERVER=mdw
            - DOCKER_GP_STANDBY_SERVER=smdw
            - DOCKER_GP_SEGMENT_SERVERS=sdw1,sdw2
            - DOCKER_GP_PRIMARY_SEGMENTS_PER_HOST=2
            - DOCKER_GP_WITH_MIRROR=true
            - HZ_NETWORK_JOIN_TCPIP_MEMBERS=adb,sdw1,sdw2
            - ADB_CLUSTER_NAME=primary_cluster
            - ADB_CLUSTER_GUID=deadbeef-feed-beef-dead-baddadfeedad
            - AGENT_JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -Xlog:gc*,safepoint:gc.log:time,uptime:filecount=100,filesize=50M -Xmx2g -Xms256m
        entrypoint: ["bash", "start_adb_service.sh"]
        extra_hosts:
            - "host.docker.internal:host-gateway"
        sysctls:
            kernel.sem: 500 1024000 200 4096
            net.unix.max_dgram_qlen: 4096
        volumes:
          - "./healthcheck.sh:/home/gpadmin/healthcheck.sh:rw"
          - "./start_adb_service.sh:/home/gpadmin/start_adb_service.sh:rw"
        networks:
          - nifinet

    smdw:
        image: "hub.adsw.io/java/gpdb6-java-ubuntu:latest"
        restart: on-failure:3
        privileged: true
        hostname: smdw
        healthcheck:
            test: 'bash /home/gpadmin/healthcheck.sh true 2 true'
        environment:
            - DOCKER_GP_CLUSTER_HOSTS=mdw,smdw,sdw1,sdw2
            - DOCKER_GP_MASTER_SERVER=mdw
            - DOCKER_GP_STANDBY_SERVER=smdw
            - DOCKER_GP_SEGMENT_SERVERS=sdw1,sdw2
            - DOCKER_GP_PRIMARY_SEGMENTS_PER_HOST=2
            - DOCKER_GP_WITH_MIRROR=true
            - HZ_NETWORK_JOIN_TCPIP_MEMBERS=adb,sdw1,sdw2
            - ADB_CLUSTER_NAME=primary_cluster
            - ADB_CLUSTER_GUID=deadbeef-feed-beef-dead-baddadfeedad
            - AGENT_JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -Xlog:gc*,safepoint:gc.log:time,uptime:filecount=100,filesize=50M -Xmx2g -Xms256m
        entrypoint: ["bash", "start_adb_service.sh"]
        extra_hosts:
            - "host.docker.internal:host-gateway"
        sysctls:
            kernel.sem: 500 1024000 200 4096
            net.unix.max_dgram_qlen: 4096
        volumes:
          - "./healthcheck.sh:/home/gpadmin/healthcheck.sh:rw"
          - "./start_adb_service.sh:/home/gpadmin/start_adb_service.sh:rw"
        networks:
          - nifinet

    postgres:
        image: "docker.io/library/postgres:12.0"
        restart: unless-stopped
        environment:
            POSTGRES_DB: 'postgres'
            POSTGRES_USER: 'nifi'
#            POSTGRES_PASSWORD: 'nifi'
        networks:
          - nifinet
        ports:
            - '5432:5432'
        healthcheck:
            test: psql -d postgres -U nifi -Atc 'SELECT 1;'
            interval: 30s
            timeout: 15s
            retries: 3

    zookeeper:
      image: 'zookeeper:latest'
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
      healthcheck:
        test: [ "CMD", "zkServer.sh", "status"]
        interval: 30s
        timeout: 15s
        retries: 3
      networks:
        - nifinet

    nifi01:
        image: apache/nifi:${NIFI_VERSION:-2.5.0}
        ports:
        - 9091:8080
        - 8001:8000 #debug port
        networks:
          - nifinet
        environment:
          - SINGLE_USER_CREDENTIALS_USERNAME=admin
          - SINGLE_USER_CREDENTIALS_PASSWORD=admin1234567890
          - NIFI_JVM_DEBUGGER=true
          - NIFI_WEB_HTTP_PORT=8080
          - NIFI_CLUSTER_IS_NODE=true
          - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
          - NIFI_ZK_CONNECT_STRING=zookeeper:2181
          - NIFI_ELECTION_MAX_WAIT=1 min
          - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey
        healthcheck:
          test: [ "CMD", "curl", "-f", "http://nifi01:8080/nifi-api/flow/status" ]
          interval: 60s
          timeout: 15s
          retries: 3
        entrypoint: [ "bash","/opt/nifi/nifi-current/prepare_nifi_configs.sh"]
        volumes:
          - "nifi_node3_data:/data"
          - "../../target/postgresql-42.6.1.jar:/opt/postgresql-42.6.1.jar"
          - "../../target/nifi-greenplum-service-nar-${NIFI_VERSION:-2.5.0}.nar:/opt/nifi/nifi-current/lib/nifi-greenplum-service-nar-${NIFI_VERSION:-2.5.0}.nar"
          - "./nifi-cluster/conf/start.sh:/opt/nifi/scripts/start.sh"
          - "./prepare_nifi_configs.sh:/opt/nifi/nifi-current/prepare_nifi_configs.sh"

    nifi02:
        image: apache/nifi:${NIFI_VERSION:-2.5.0}
        ports:
          - 9092:8080
          - 8002:8000
        networks:
          - nifinet
        environment:
          - SINGLE_USER_CREDENTIALS_USERNAME=admin
          - SINGLE_USER_CREDENTIALS_PASSWORD=admin1234567890
          - NIFI_JVM_DEBUGGER=true
          - NIFI_WEB_HTTP_PORT=8080
          - NIFI_CLUSTER_IS_NODE=true
          - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
          - NIFI_ZK_CONNECT_STRING=zookeeper:2181
          - NIFI_ELECTION_MAX_WAIT=1 min
          - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey
        healthcheck:
          test: [ "CMD", "curl", "-f", "http://nifi02:8080/nifi-api/flow/status" ]
          interval: 60s
          timeout: 15s
          retries: 3
        entrypoint: [ "bash","/opt/nifi/nifi-current/prepare_nifi_configs.sh" ]
        volumes:
          - "nifi_node3_data:/data"
          - "../../target/postgresql-42.6.1.jar:/opt/postgresql-42.6.1.jar"
          - "../../target/nifi-greenplum-service-nar-${NIFI_VERSION:-2.5.0}.nar:/opt/nifi/nifi-current/lib/nifi-greenplum-service-nar-${NIFI_VERSION:-2.5.0}.nar"
          - "./nifi-cluster/conf/start.sh:/opt/nifi/scripts/start.sh"
          - "./prepare_nifi_configs.sh:/opt/nifi/nifi-current/prepare_nifi_configs.sh"

    nifi03:
        image: apache/nifi:${NIFI_VERSION:-2.5.0}
        ports:
          - 9093:8080
          - 8003:8000
        networks:
          - nifinet
        environment:
          - SINGLE_USER_CREDENTIALS_USERNAME=admin
          - SINGLE_USER_CREDENTIALS_PASSWORD=admin1234567890
          - NIFI_JVM_DEBUGGER=true
          - NIFI_WEB_HTTP_PORT=8080
          - NIFI_CLUSTER_IS_NODE=true
          - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
          - NIFI_ZK_CONNECT_STRING=zookeeper:2181
          - NIFI_ELECTION_MAX_WAIT=1 min
          - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey
        healthcheck:
          test: [ "CMD", "curl", "-f", "http://nifi03:8080/nifi-api/flow/status" ]
          interval: 60s
          timeout: 15s
          retries: 3
        entrypoint: [ "bash","/opt/nifi/nifi-current/prepare_nifi_configs.sh" ]
        volumes:
          - "nifi_node3_data:/data"
          - "../../target/postgresql-42.6.1.jar:/opt/postgresql-42.6.1.jar"
          - "../../target/nifi-greenplum-service-nar-${NIFI_VERSION:-2.5.0}.nar:/opt/nifi/nifi-current/lib/nifi-greenplum-service-nar-${NIFI_VERSION:-2.5.0}.nar"
          - "./nifi-cluster/conf/start.sh:/opt/nifi/scripts/start.sh"
          - "./prepare_nifi_configs.sh:/opt/nifi/nifi-current/prepare_nifi_configs.sh"

volumes:
  nifi_node1_data:
  nifi_node2_data:
  nifi_node3_data:

networks:
  nifinet: