# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM apache/nifi:1.26.0

USER root
# Copy necessary nar and configuration files

COPY --from=root target/nifi-greenplum-service-nar-1.26.0.nar /opt/nifi/nifi-current/lib/
COPY ./conf/* /opt/nifi/nifi-current/conf/
# Add permissions
RUN chown -R nifi:nifi /opt/nifi/nifi-current/conf && \
    chmod -R 755 /opt/nifi/nifi-current/conf

USER nifi
